version: 2.1

jobs:
  deploy:
    machine:
      image: nginx:stable
    steps:
      - checkout
      - run:
          name: Copy path
          command: |
            ls -la
            pwd
            
workflows:
  version: 2
  execute_bulk:
    jobs:
      - deploy